#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-http
Version  : 2.0.3
Release  : 7
URL      : https://rubygems.org/downloads/http-2.0.3.gem
Source0  : https://rubygems.org/downloads/http-2.0.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-coveralls
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-docile
BuildRequires : rubygem-domain_name
BuildRequires : rubygem-http-cookie
BuildRequires : rubygem-http-form_data
BuildRequires : rubygem-mime-types
BuildRequires : rubygem-netrc
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rest-client
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-simplecov-html
BuildRequires : rubygem-term-ansicolor
BuildRequires : rubygem-thor
BuildRequires : rubygem-tins
BuildRequires : rubygem-unf
BuildRequires : rubygem-unf_ext

%description
# ![http.rb](https://raw.github.com/httprb/http.rb/master/logo.png)
[![Gem Version](https://badge.fury.io/rb/http.svg)](https://rubygems.org/gems/http)
[![Build Status](https://secure.travis-ci.org/httprb/http.svg?branch=master)](https://travis-ci.org/httprb/http)
[![Code Climate](https://codeclimate.com/github/httprb/http.svg?branch=master)](https://codeclimate.com/github/httprb/http)
[![Coverage Status](https://coveralls.io/repos/httprb/http/badge.svg?branch=master)](https://coveralls.io/r/httprb/http)
[![MIT licensed](https://img.shields.io/badge/license-MIT-blue.svg)](https://github.com/httprb/http/blob/master/LICENSE.txt)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n http-2.0.3
gem spec %{SOURCE0} -l --ruby > rubygem-http.gemspec

%build
export LANG=C
gem build rubygem-http.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
http-2.0.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/http-2.0.3.gem
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/.coveralls.yml
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/.rspec
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/.rubocop.yml
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/CHANGES.md
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/Guardfile
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/README.md
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/http.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/chainable.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/client.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/connection.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/content_type.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/errors.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/headers.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/headers/known.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/headers/mixin.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/mime_type.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/mime_type/adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/mime_type/json.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/options.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/redirector.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/request.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/request/writer.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/response.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/response/body.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/response/parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/response/status.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/response/status/reasons.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/timeout/global.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/timeout/null.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/timeout/per_operation.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/uri.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/lib/http/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/logo.png
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http/client_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http/content_type_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http/headers/mixin_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http/headers_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http/options/body_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http/options/form_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http/options/headers_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http/options/json_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http/options/merge_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http/options/new_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http/options/proxy_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http/options_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http/redirector_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http/request/writer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http/request_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http/response/body_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http/response/status_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http/response_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http/uri_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/lib/http_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/regression_specs.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/support/black_hole.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/support/capture_warning.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/support/dummy_server.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/support/dummy_server/servlet.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/support/http_handling_shared.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/support/proxy_server.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/support/servers/config.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/support/servers/runner.rb
/usr/lib64/ruby/gems/2.3.0/gems/http-2.0.3/spec/support/ssl_helper.rb
/usr/lib64/ruby/gems/2.3.0/specifications/http-2.0.3.gemspec
